# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20171224_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Dia')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Docente')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Hora')),
            ],
        ),
    ]
