# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_hora_horaf'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Dia')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.Hora')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf.GradoSeccion')),
            ],
        ),
    ]
