# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_horarioseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='horarioDocente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='conf.HorarioDocente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='horarioSeccion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='conf.HorarioSeccion'),
            preserve_default=False,
        ),
    ]
